name: Application CI/CD

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
    paths: 
      - 'app/build.gradle'
      
  workflow_dispatch:

jobs:
  check:
    name: Check gradle config
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Expose version name
        uses: michpohl/android-expose-version-name-action@v1.0.0
        with:
          expose-version-name: 'true'
          expose-version-code: 'false'
          
      - run: 'echo "$VERSION_NAME" > VERSION'
        shell: bash
        env:
          VERSION_NAME: ${{env.ANDROID_VERSION_NAME}}
          
      - uses: actions/upload-artifact@v2
        with:
          name: Android version name
          path: VERSION
  build:
    name: Build app bundle
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build APK
        run: ./gradlew build
        
      - name: Build bundle
        run: ./gradlew bundleRelease
        
      - uses: actions/upload-artifact@v2
        with:
          name: Unsigned APK
          path: /home/runner/work/EffnerApp/EffnerApp/app/build/outputs/apk/release/app-release-unsigned.apk
          
      - uses: actions/upload-artifact@v2
        with:
          name: Unsigned app bundle
          path: /home/runner/work/EffnerApp/EffnerApp/app/build/outputs/bundle/release/app-release.aab
        
  sign:
    name: Sign app bundle
    runs-on: ubuntu-latest
    needs: [check, build]
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: Android version name
          
      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(cat VERSION)"
          
      - uses: actions/download-artifact@v2
        with:
          name: Unsigned APK
          
      - uses: actions/download-artifact@v2
        with:
          name: Unsigned app bundle
          path: bundle/
    
      - uses: r0adkll/sign-android-release@v1
        name: Sign app bundle
        id: sign_app
        with:
          releaseDirectory: /home/runner/work/EffnerApp/EffnerApp/bundle
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.3"
      
      - uses: actions/upload-artifact@v2
        with:
          name: Signed app bundle
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ steps.getversion.outputs.version }}
          files: |
            app-release-unsigned.apk
            ${{steps.sign_app.outputs.signedReleaseFile}}
           
  upload:
    name: Upload & release app on Google Play
    runs-on: ubuntu-latest
    needs: [sign]
  
    steps:
      - uses: actions/checkout@v2
          
      - uses: actions/download-artifact@v2
        with:
          name: Signed app bundle
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: de.effnerapp.effner
          releaseFiles: 'app-release.aab'
          track: alpha
          whatsNewDirectory: dist/
